version: "3.8"
services:
  nginx:
    container_name: nginx
    build: ./backend/docker/nginx
    command: nginx -g "daemon off;"
    links:
      - php
      - redis
      - mysql
    ports:
      - "8182:80"
    volumes:
      - ./backend/src:/var/www/html
  php:
    container_name: php
    build: ./backend/docker/php
    command: sh -c "composer install"
    ports:
      - "9000:9000"
    volumes:
      - ./backend/src:/var/www/html
    working_dir: /var/www/html
  mysql:
    container_name: mysql
    build: ./backend/docker/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./backend/database/mysql:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8085:80
  redis:
    container_name: redis
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    image: 'redis:alpine'
    ports:
      - '6379:6379'
  frontend:
    container_name: frontend
    links:
      - nginx
    build: ./frontend
    ports:
      - "8282:80"
    volumes:
      - ./frontend:/usr/share/nginx/html